### ISSUE TITLE
Write all tests and update readme

### ISSUE THREAD

**Issue by lk-geimfari** [mimesis-lab/pytest-mimesis#1]
We need to write test for all providers and update README.md

**Comment by lk-geimfari** [comment]
@wikkiewikkie Are you interested?

**Comment by wikkiewikkie** [comment]
@lk-geimfari  Is the idea here that someone can use Elizabeth as part of the test suite for their project?

For example, they have a function that should check that the user input a valid e-mail address.  In the test for that function, they could use Elizabeth to generate fake e-mail addresses as input?

**Comment by wikkiewikkie** [comment]
```python
from pytest-elizabeth import personal
from myproject import validate_email

def test_validate_email(personal):
    result = validate_email(personal.email())
    assert result
```

Something like that?

**Comment by lk-geimfari** [comment]
@wikkiewikkie Yeah. For case like in example above and for another cases. It's a plugin and we should not import nothing

```
def test_generic(personal, elizabeth_locale):
"""Test elizabeth fixture."""
    assert isinstance(generic, elizabeth.Personal)
    assert personal.name()
    assert elizabeth_locale == 'en'
```

We use fixtures.

**Comment by lk-geimfari** [comment]
@wikkiewikkie

**Comment by lk-geimfari** [comment]
@wikkiewikkie Now you're collaborator and we can work on it together. You can merge PRs without me.

**Comment by lk-geimfari** [comment]
@wikkiewikkie Also, if you interested in testing tools i have an experimental project that provider regex patterns. [Here](https://github.com/lk-geimfari/expynent) you can look at details

**Comment by lk-geimfari** [comment]
We also can do from `expynent` something useful.

**Comment by wikkiewikkie** [comment]
@lk-geimfari I will check out expynent

**Comment by lk-geimfari** [comment]
@wikkiewikkie Okay. Thanks!
