### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by sobolevn** [mimesis-lab/pytest-mimesis#4]
@lk-geimfari I don't have an access to PYPI. Can you please allow me to publish new versions?

**Comment by lk-geimfari** [comment]
@sobolevn We have not published it as I know.

**Comment by lk-geimfari** [comment]
@sobolevn I mean that you can publish it on your pypi account.

**Comment by lk-geimfari** [comment]
![screenshot from 2018-06-17 13-38-35](https://user-images.githubusercontent.com/15812620/41507081-d6b11cd0-7233-11e8-9214-5deaae63c44f.png)

**Comment by sobolevn** [comment]
Oh, ok. I will invite you as a collaborator. https://pypi.org/project/pytest-mimesis/

**Comment by sobolevn** [comment]
@lk-geimfari sent you an invite.

**Comment by lk-geimfari** [comment]
@sobolevn Thank you!
