### ISSUE TITLE
Fix links after the migration process

### ISSUE THREAD

**Issue by sobolevn** [mimesis-lab/pytest-mimesis#74]
This is now an official `pytest` plugin!

I solute to @lk-geimfari for building `mimesis` and this plugin.
The next step is to fix all links that point to the old repo. And make a new patch release.

**Comment by sobolevn** [comment]
There are currently some access issues, but we are working on it.

**Comment by lk-geimfari** [comment]
@sobolevn Great! Thank you for your contributions to mimesis and other libraries based on mimesis!

**Comment by hugovk** [comment]
Please see PR #75.
